accessibilityJob: false
alwaysRunPostSteps: true
appium: null
autosplit: true
betaFeature:
    setPartiallyCompletedAsCompleted: false
captureScreenRecordingForScenarios: false
codeDirectory: KarateAPI
collectLocalGitData: true
combineTasksInMatrixMode: false
concurrency: 10
cypress: false
differentialUpload:
    enabled: true
    forcedDisabled: false
    ttlHours: 24
dynamicAllocation: false
errorCategorizedOnFailureOnly: false
framework:
    additional_args: null
    args:
        appId: ""
        appPath: ""
        artifacts: false
        avoidAppLaunch: false
        customData: {}
        deviceSelectionStrategy: ""
        devices: []
        disableReleaseDevice: false
        filters:
            attributes: []
        fixedIP: ""
        isRealMobile: null
        isVirtualDevice: false
        language: ""
        locale: ""
        minorOsVersion: false
        mitmProxy: false
        mobileDC: null
        networkHar: false
        otherApps: []
        platformName: ""
        playwrightRD: false
        preservedDevice: false
        queueTimeout: 0
        resignApp: true
        shards:
            mappings: []
        skipInstall: false
        skipUninstallPreviousBuild: false
        skipXMLOnRun: false
        smartUI: null
        testSuiteAppId: ""
        testSuitePath: ""
        uninstallPreviousBuild: false
        xcTestPlanId: ""
        xcTestPlanPath: ""
    baseCommand: ""
    defaultReports: false
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    downloadURL: ""
    flags: []
    isTestNGXMLSuite: false
    licenseKey: ""
    name: ""
    runnerFlags: []
    toscaArgs: null
    userdefinediscovery: false
    version: ""
    workingDirectory: ""
globalPost:
    commands:
        - ls -la
        - pwd
        - cd build; ls -la
    completed: false
    mode: remote
    runson: ""
    shell: ""
    workingDirectory: ""
globalPre:
    cache: false
    commands: []
    completed: false
    location: ""
    maxRetries: 0
    mode: ""
    runson: ""
    shell: ""
    type: ""
    workingDirectory: ""
    yamlPath: null
jobID: 4473ef39-1159-4c95-b64c-f06490c3f392
jobLabel:
    - Karate
    - API
key: LT_Pf3gLJhEz0t7X2h7gQca0y2fAzQJVUl6SwRxPNPlsPatcXf
localHTTPProxy: ""
maxRetriesPreSteps: 0
meta: {}
partialReports:
    type: html
    location: build/karate-reports
    frameworkName: karate
    email:
        to: []
        metaInfo: []
        linkValidity: 0
    configPath: ""
    configPathURL: ""
platformConfig: null
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
preDirectives:
    commands: []
    maxRetries: 0
    shell: ""
    workingDirectory: ""
project:
    id: 01JV49A54FRP0RYJD3VWGSQYVV
    name: Karate API Project
    type: custom
projectpath: ""
regionConfig:
    storage:
        enabled: false
        name: ""
        platform: azure
        region: ""
    vm: []
report: true
runson: mac
runtime:
    addons: []
    language: java
    opts: {}
    version: "17"
scenarioCommandStatusOnly: true
slackChannel: ""
sourcePayload:
    verifySSL: true
sprofilePath: ""
storageType: ""
testDiscovery:
    command: snooper --targetOs=mac --featureFilePaths=src/test/resources/apis/features --frameWork=java
    mode: remote
    type: raw
testDiscoveryResultV3: []
testRunnerCommand: |
    echo "Running test: $test"
    ./gradlew test --tests APIRunner  -Dkarate.options=$test
testSuites: []
triggerMode: false
tunnelOpts:
    testsPerTunnel: 10
unzipPayload: false
uploadArtefacts:
    - email:
        linkValidity: 0
        metaInfo: []
        to: []
      name: Log File
      path:
        - target/
    - email:
        linkValidity: 0
        metaInfo: []
        to: []
      name: Karate Report
      path:
        - build/karate-reports/
user: dhakshathamin
version: "0.1"
waitForArtefactsUpload: false
whiteLabelProductTag: ""
