environment:
  EMAIL_NOTIFICATION: Vykuntavasu.Uppala@wellsfargo.com,shivam.uniyal@wellsfargo.com
  RELEASE_NUMBER: Release_1.0
buildPack:
  name: baseImage
appListProperties:
  publish:
    tag: o00o455
  containerRegistries:  # optional: override registries endpoint (available as of v2021.09.0)
    acr:
      push:  true   # optional: push certified image to acr. default: false
      url: acrscussandboxmsacck1.azurecr.io    #acrscusprodaks001.azurecr.io (for AD-ENT ACR) # acrscusnonprodmsacqa1.azurecr.io (for QA-ENT ACR) # optional: specify acr url, default: acrscusprodaks001.azurecr.io (as of 2022.06.01)

  prisma:
    continueOnFailure: true
    enablePrismaScanSaaSMode: true
pipelines:
  release:
    stages:
      - name: Publish
        when:
          branch:
            - main
            - master
            - /^release\/.*$/
      - name: SCM Tag
        when:
          branch:
            - main
            - master
            - /^release\/.*$/
  snapshot:
    stages:
      - name: Publish
        disable: true
      - name: SCM Tag
        disable: true
